### ISSUE TITLE
Wait for status before calling the next node update method

### ISSUE THREAD

**Issue by gaurav-chawla** [srohatgi/graph#10]
Currently, Sync method calls the next node's update method without it to be ready. To avoid that we have to add the polling inside the update method so the next method dependencies are fulfilled. 
Builders should implement `IsReady() bool` method and Sync method should call it before calling the next node's update method.

**Comment by srohatgi** [comment]
Isn't it better to have a resource poller that you can introduce in the graph itself (you can configure/ manage also)? The library poller seems to be unnecessary.

**Comment by srohatgi** [comment]
maybe a solution is to require an event producer/ consumer pattern. the library may put the graph in "holding pattern" until it receives an appropriate trigger event. 

lets discuss...

**Comment by srohatgi** [comment]
#13
